#file for package detection 
#Do not use Japanese in this file!

library(colorspace)
library(cowplot)
library(dplyr)
library(DT)
library(geofacet)
library(ggplot2)
library(knitr)
library(leaflet)
library(magrittr)
library(officer)
library(openxlsx)
library(plotly)
library(purrr)
library(readr)
library(RColorBrewer)
library(sf)
library(shiny)
library(shinyWidgets)
library(stringr)
library(tidyr)
library(shinycssloaders)
library(showtext)
library(shinydashboard)
